version: '3.7'
services:
    angular:
        container_name: angular
        build: angular
        volumes:
            - ./angular:/usr/app

    association-web:
      container_name: association-web
      build: elastic
      volumes:
        - ./association_web:/usr/src

    indexer-elk:
        container_name: indexer-elk
        build: elastic
        volumes:
            - ./elastic:/usr/src
