version: '3.7'
services:
    angular:
        container_name: angular
        build: angular
        volumes:
            - ./angular:/usr/app
            - ./angular/logs:/root/.npm/_logs/
            - /usr/app/node_modules
            - /usr/app/.angular

    association-web:
      container_name: association-web
      build: association_web
      volumes:
        - ./association_web:/usr/src

    indexer-elk:
        container_name: indexer-elk
        build: elastic
        volumes:
            - ./elastic:/usr/src
