version: '3.7'
services:
    angular:
        container_name: angular
        build: angular
        volumes:
            - ./angular:/usr/app
    
    indexer-elk:
        container_name: indexer-elk
        build: elastic
        volumes:
            - ./elastic:/usr/src