settings:
  index:
    # single node, no sharding
    number_of_shards: 1
    number_of_replicas: 0
    refresh_interval: 60s
mappings:
  dynamic: false
  properties:
    id: &fr_text
      type: text
      analyzer: french
    titre: *fr_text
    objet: *fr_text
    adrs_libvoie: *fr_text
    adrs_codepostal: *fr_text
    adrs_libcommune: *fr_text
    adrs_typevoie: *fr_text
    adrs_numvoie: *fr_text
    adrg_libvoie: *fr_text
    adrg_codepostal: *fr_text