version: '3.7'
services:
    asso-db:
        container_name: asso-db
        build: asso-db
        ports:
            - "5432:5432"
        volumes:
            - ./asso-db/:/root/
        environment:
            - POSTGRES_DB=associations
            - POSTGRES_USER=u_asso_admin
            - POSTGRES_PASSWORD=u_asso_admin

    back-java:
        container_name: asso-web
        build: association_web
        restart: on-failure
        volumes:
            - ./association_web/jar:/root/jar
        depends_on:
            - asso-db

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        container_name: es
        environment:
            - discovery.type=single-node
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./esdata:/usr/share/elasticsearch/data

    #kibana:
    #    image: docker.elastic.co/kibana/kibana:7.16.2
    #    ports:
    #          - "5601:5601"
    #    environment:
    #      ELASTICSEARCH_HOSTS: http://es:9200
    #    depends_on:
    #        - es

    nginx:
        container_name: asso-app
        image: nginx:1.20.0-alpine
        restart: on-failure
        volumes:
            - ./nginx/front/public:/usr/src/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/certbot/www:/var/www/certbot/:ro
            - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - back-java
            - asso-db
            - es

    app-certbot:
        container_name: cert-app
        image: certbot/certbot:latest
        volumes:
            - ./nginx/certbot/www/:/var/www/certbot/:rw
            - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
            - ./nginx/certbot/logs/:/var/log/letsencrypt
        depends_on:
            - nginx
        command: certonly -v --webroot --webroot-path /var/www/certbot/ --email your-email@sacquet-association.org --agree-tos -d sacquet-association.org -d www.sacquet-association.org

    import:
        container_name: import-association
        build: import-association
        volumes:
            - ./import-association/import:/root/import
            - ./import-association/indexer:/root/indexer
        depends_on:
            - asso-db
            - es
            # - kibana
